#!/usr/bin/env python3

from pathlib import Path

PROJECT = "TawilOS Mobile"

ninja = r"""
# Auto-generated by configure.py
# Do not edit build.ninja manually.

builddir = build

cc = gcc
ld = ld
grub_mkrescue = grub-mkrescue
qemu = qemu-system-i386

cflags = -m32 -ffreestanding -fno-pie -fno-stack-protector -Wall -Wextra
ldflags = -m elf_i386 -T kernel/linker.ld

rule cc
  command = $cc $cflags -c $in -o $out
  description = CC $out

rule link
  command = $ld $ldflags -o $out $in
  description = LD $out

rule mkdir
  command = mkdir -p $out
  description = MKDIR $out

rule copy
  command = cp $in $out
  description = COPY $out

rule grub_cfg
  command = printf 'set timeout=0\nset default=0\n\nmenuentry "TawilOS Mobile" {\n    multiboot /boot/tawilos.bin\n    boot\n}\n' > $out
  description = GRUBCFG $out

rule iso
  command = $grub_mkrescue -o $out build/iso
  description = ISO $out

rule run
  command = $qemu -cdrom build/images/tawilos.iso
  description = RUN TawilOS Mobile

rule clean
  command = rm -rf build/output build/iso build/images build/*.stamp
  description = CLEAN

build build/output: mkdir
build build/iso/boot/grub: mkdir
build build/images: mkdir

build build/output/main.o: cc kernel/main.c | build/output
build build/output/tawilos.bin: link build/output/main.o | build/output

build build/iso/boot/tawilos.bin: copy build/output/tawilos.bin | build/iso/boot/grub
build build/iso/boot/grub/grub.cfg: grub_cfg | build/iso/boot/grub

build build/images/tawilos.iso: iso build/iso/boot/tawilos.bin build/iso/boot/grub/grub.cfg | build/images

build iso: phony build/images/tawilos.iso
build kernel: phony build/output/tawilos.bin
build run: run build/images/tawilos.iso
build clean: clean

default iso
"""

Path("build.ninja").write_text(ninja.strip() + "\n")

print("Generated build.ninja")
print("Run:")
print("  ninja")
print("  ninja run")
print("  ninja clean")
